root: "https://fmfm.ozonicsky.com/"

bot:
  ua: "Mozilla/5.0 (compatible; fmfm crawler/1.0; +https://fmfm.ozonicsky.com)"

provider:
  twitter:
    api_key: <%= ENV['TWITTER_API_KEY'] %>
    api_secret: <%= ENV['TWITTER_API_SECRET'] %>
